### ISSUE TITLE
Web UI not accessible

### ISSUE THREAD

**Issue by OnnoH** [linuxserver/docker-oscam#27]
## Expected Behavior
WebInterface should be available on http://localhost:8888 or http://<my.ip.add.ress>:8888

`docker exec -ti oscam bash` should work as well.

## Current Behavior
Startup logs indicate an error (exitcode 267). But not what the error entails.

Inspecting the running container is not possible on the account of a failing (without feedback) `docker exec`

## Steps to Reproduce
1. Create a folder with oscam.conf, oscam.user and oscam.server files
2. Adapted the docker-compose.yml to use this folder in volume specification
3. Started container with `docker-compose up -d`
4. Tailed the log `docker logs -f oscam`

## Environment
**OS:**  Raspbian GNU/Linux 9 (stretch)    
**CPU architecture:** arm32/armhf      
**How docker service was installed:**  Preinstalled on HypriotOS Image
**Docker version:** Docker version 18.06.3-ce, build d7080c1

## Command used to create docker container (run/create/compose/screenshot)
```
---
version: "2.1"
services:
  oscam:
    image: linuxserver/oscam
    container_name: oscam
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/pirate/config:/config
    ports:
      - 8888:8888
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
```

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 267.
[cont-init.d] 10-adduser: executing...
[cont-init.d] 10-adduser: exited 267.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 267.
[cont-init.d] 99-custom-files: executing...
[cont-init.d] 99-custom-files: exited 267.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```
