### ISSUE TITLE
sh: pzapit: not found

### ISSUE THREAD

**Issue by klara31** [linuxserver/docker-oscam#28]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Current Behavior
When starting the container, after a few moments the message ```sh: pzapit: not found``` appears. The container is running, but oscam is not working

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**
CPU architecture: arm64
**How docker service was installed:**
From the official docker repo.

## Docker logs
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    0
User gid:    0
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
sh: pzapit: not found
```

**Comment by tobbenb** [comment]
Please fill in all info we ask for!
Try running it as a normal user and not root.

**Comment by klara31** [comment]
When running the container as non-root, oscam gives the following error:
``` 
2021/02/12 23:10:22 364424E5 r   (reader) smargo [smartreader] libusb_open error LIBUSB_ERROR_ACCESS : the user has insufficient permissions
```

My docker-compose.yml:
```
  oscam:
    image: ghcr.io/linuxserver/oscam:latest
    privileged: true
    container_name: oscam
    environment:
      - PUID=1000
      - PGID=100
      - TZ=${TZ}
    volumes:
      - ${USERDIR}/oscam:/config
      - /home/pi/picons/picons:/picons
    ports:
      - 8888:8888
      - 9000:9000
    network_mode: bridge
    devices:
      - /dev/bus/usb/001/004:/dev/bus/usb/001/004
    restart: unless-stopped
```
Removing the ```privileged: true``` has no effect. To get oscam running, I need ```PUID=0```.
