### ISSUE TITLE
Healthcheck support

### ISSUE THREAD

**Issue by S474N** [linuxserver/docker-oscam#38]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Healthcheck support to docker-compose.yml

### Reason for change

Benefit is for simple checking, that everything is ok.

**Comment by thespad** [comment]
We don't add built-in healthchecks to our images, but you can always add your own via your [compose](https://docs.docker.com/compose/compose-file/compose-file-v2/#healthcheck).

**Comment by S474N** [comment]
> 

Thank you, for your suggestion. Do you know, what command may I use?

**Comment by thespad** [comment]
At a very basic level something like
```yaml
healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost:8888"]
  start_period: 20s
  interval: 5s
  retries: 5
  timeout: 5s
```
